# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 09:30
from __future__ import unicode_literals

from django.conf import settings
import django.core.files.storage
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LikedMedia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('', ''), ('twitter', 'twitter'), ('instagram', 'instagram'), ('weibo', 'weibo')], help_text='Social platform provider name', max_length=50)),
                ('rid', models.CharField(db_index=True, help_text='id on origin platform', max_length=100)),
                ('rcode', models.CharField(db_index=True, help_text='code/id on other platform', max_length=100)),
                ('rlink', models.TextField()),
                ('type', models.TextField(choices=[('video', 'video'), ('audio', 'audio'), ('photo', 'photo')], default='photo')),
                ('text', models.TextField(blank=True, null=True)),
                ('tags', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('timestamp', models.DateTimeField(auto_now=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
                ('rjson', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='MediaInstance',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('video', 'video'), ('audio', 'audio'), ('photo', 'photo')], default='photo', max_length=50)),
                ('quality', models.CharField(choices=[(0, 'origin'), (9, 'THUMB'), (10, 'low'), (20, 'medium'), (30, 'high')], default=20, max_length=50)),
                ('instance', models.FileField(blank=True, help_text='Media instance storage', null=True, storage=django.core.files.storage.FileSystemStorage(), upload_to='')),
                ('origin_url', models.TextField(blank=True, null=True)),
                ('height', models.IntegerField(blank=True, null=True)),
                ('width', models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='MyMedia',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('media', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='weinsta.Media')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='SocialUser',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('', ''), ('twitter', 'twitter'), ('instagram', 'instagram'), ('weibo', 'weibo')], help_text='Social platform provider name', max_length=50)),
                ('username', models.CharField(db_index=True, help_text='username on origin platform', max_length=50)),
                ('rid', models.CharField(db_index=True, help_text='id on origin platform', max_length=100)),
                ('fullname', models.CharField(blank=True, max_length=200, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('website', models.TextField(blank=True, null=True)),
                ('is_artist', models.BooleanField(default=False)),
                ('is_publisher', models.BooleanField(default=False)),
                ('picture', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weinsta.MediaInstance')),
            ],
        ),
        migrations.CreateModel(
            name='SysConfig',
            fields=[
                ('name', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('value', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='media',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='author', to='weinsta.SocialUser'),
        ),
        migrations.AddField(
            model_name='media',
            name='high_res',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='high_res_media', to='weinsta.MediaInstance'),
        ),
        migrations.AddField(
            model_name='media',
            name='instance',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='instance_media', to='weinsta.MediaInstance'),
        ),
        migrations.AddField(
            model_name='media',
            name='mentions',
            field=models.ManyToManyField(related_name='mentions', to='weinsta.SocialUser'),
        ),
        migrations.AddField(
            model_name='media',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='owner', to='weinsta.SocialUser'),
        ),
        migrations.AddField(
            model_name='media',
            name='thumb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='thumb_media', to='weinsta.MediaInstance'),
        ),
        migrations.AddField(
            model_name='media',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='likedmedia',
            name='media',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weinsta.Media'),
        ),
        migrations.AddField(
            model_name='likedmedia',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='socialuser',
            unique_together=set([('provider', 'username'), ('provider', 'rid')]),
        ),
        migrations.AlterUniqueTogether(
            name='media',
            unique_together=set([('provider', 'rcode'), ('provider', 'rid')]),
        ),
    ]
