# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 04:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weinsta', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='media',
            name='low_res',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='low_res_media', to='weinsta.MediaInstance'),
        ),
        migrations.AddField(
            model_name='media',
            name='mid_res',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mid_res_media', to='weinsta.MediaInstance'),
        ),
        migrations.AddField(
            model_name='mediainstance',
            name='url_hash',
            field=models.CharField(db_index=True, default=None, max_length=50, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media',
            name='provider',
            field=models.CharField(choices=[('', ''), ('instagram', 'instagram'), ('weibo', 'weibo'), ('twitter', 'twitter')], help_text='Social platform provider name', max_length=50),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.TextField(choices=[('audio', 'audio'), ('photo', 'photo'), ('video', 'video')], default='photo'),
        ),
        migrations.AlterField(
            model_name='mediainstance',
            name='quality',
            field=models.CharField(choices=[(0, 'origin'), (9, 'thumb'), (10, 'low'), (20, 'medium'), (30, 'high')], default=20, max_length=50),
        ),
        migrations.AlterField(
            model_name='mediainstance',
            name='type',
            field=models.CharField(choices=[('audio', 'audio'), ('photo', 'photo'), ('video', 'video')], default='photo', max_length=50),
        ),
        migrations.AlterField(
            model_name='socialuser',
            name='provider',
            field=models.CharField(choices=[('', ''), ('instagram', 'instagram'), ('weibo', 'weibo'), ('twitter', 'twitter')], help_text='Social platform provider name', max_length=50),
        ),
    ]
