# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 05:19
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weinsta', '0002_auto_20170914_1207'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='media',
            name='instance',
        ),
        migrations.AddField(
            model_name='media',
            name='pic_high_res',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pic_high_res_media', to='weinsta.MediaInstance'),
        ),
        migrations.AddField(
            model_name='media',
            name='pic_low_res',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pic_low_res_media', to='weinsta.MediaInstance'),
        ),
        migrations.AddField(
            model_name='media',
            name='pic_mid_res',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pic_mid_res_media', to='weinsta.MediaInstance'),
        ),
        migrations.AlterField(
            model_name='media',
            name='provider',
            field=models.CharField(choices=[('', ''), ('twitter', 'twitter'), ('weibo', 'weibo'), ('instagram', 'instagram')], help_text='Social platform provider name', max_length=50),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.TextField(choices=[('audio', 'audio'), ('video', 'video'), ('photo', 'photo')], default='photo'),
        ),
        migrations.AlterField(
            model_name='mediainstance',
            name='type',
            field=models.CharField(choices=[('audio', 'audio'), ('video', 'video'), ('photo', 'photo')], default='photo', max_length=50),
        ),
        migrations.AlterField(
            model_name='socialuser',
            name='provider',
            field=models.CharField(choices=[('', ''), ('twitter', 'twitter'), ('weibo', 'weibo'), ('instagram', 'instagram')], help_text='Social platform provider name', max_length=50),
        ),
    ]
