# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-14 05:52
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weinsta', '0003_auto_20170914_1319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='author', to='weinsta.SocialUser'),
        ),
        migrations.AlterField(
            model_name='media',
            name='high_res',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='high_res_media', to='weinsta.MediaInstance'),
        ),
        migrations.AlterField(
            model_name='media',
            name='low_res',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='low_res_media', to='weinsta.MediaInstance'),
        ),
        migrations.AlterField(
            model_name='media',
            name='mid_res',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mid_res_media', to='weinsta.MediaInstance'),
        ),
        migrations.AlterField(
            model_name='media',
            name='owner',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner', to='weinsta.SocialUser'),
        ),
        migrations.AlterField(
            model_name='media',
            name='pic_high_res',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pic_high_res_media', to='weinsta.MediaInstance'),
        ),
        migrations.AlterField(
            model_name='media',
            name='pic_low_res',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pic_low_res_media', to='weinsta.MediaInstance'),
        ),
        migrations.AlterField(
            model_name='media',
            name='pic_mid_res',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pic_mid_res_media', to='weinsta.MediaInstance'),
        ),
        migrations.AlterField(
            model_name='media',
            name='provider',
            field=models.CharField(choices=[('', ''), ('instagram', 'instagram'), ('weibo', 'weibo'), ('twitter', 'twitter')], help_text='Social platform provider name', max_length=50),
        ),
        migrations.AlterField(
            model_name='media',
            name='thumb',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='thumb_media', to='weinsta.MediaInstance'),
        ),
        migrations.AlterField(
            model_name='media',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='socialuser',
            name='picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weinsta.MediaInstance'),
        ),
        migrations.AlterField(
            model_name='socialuser',
            name='provider',
            field=models.CharField(choices=[('', ''), ('instagram', 'instagram'), ('weibo', 'weibo'), ('twitter', 'twitter')], help_text='Social platform provider name', max_length=50),
        ),
    ]
