# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 12:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weinsta', '0004_auto_20170914_1352'),
    ]

    operations = [
        migrations.RenameField(
            model_name='media',
            old_name='pic_high_res',
            new_name='pic_high',
        ),
        migrations.RenameField(
            model_name='media',
            old_name='pic_low_res',
            new_name='pic_low',
        ),
        migrations.RemoveField(
            model_name='media',
            name='high_res',
        ),
        migrations.RemoveField(
            model_name='media',
            name='low_res',
        ),
        migrations.RemoveField(
            model_name='media',
            name='mid_res',
        ),
        migrations.RemoveField(
            model_name='media',
            name='pic_mid_res',
        ),
        migrations.AddField(
            model_name='media',
            name='high',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='high_quality_media', to='weinsta.MediaInstance'),
        ),
        migrations.AddField(
            model_name='media',
            name='low',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='low_quality_media', to='weinsta.MediaInstance'),
        ),
        migrations.AddField(
            model_name='media',
            name='origin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='origin_media', to='weinsta.MediaInstance'),
        ),
        migrations.AlterField(
            model_name='media',
            name='rcode',
            field=models.CharField(db_index=True, help_text='code/id on origin platform', max_length=100),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.TextField(choices=[('video', 'video'), ('audio', 'audio'), (None, 'unknown'), ('photo', 'photo')], default='photo'),
        ),
        migrations.AlterField(
            model_name='mediainstance',
            name='quality',
            field=models.CharField(choices=[(0, 'origin'), (9, 'thumb'), (10, 'low'), (30, 'high')], default=0, max_length=50),
        ),
        migrations.AlterField(
            model_name='mediainstance',
            name='type',
            field=models.CharField(choices=[('video', 'video'), ('audio', 'audio'), (None, 'unknown'), ('photo', 'photo')], default='photo', max_length=50),
        ),
    ]
