# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-15 13:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weinsta', '0005_auto_20170915_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='media',
            name='provider',
            field=models.CharField(choices=[('', ''), ('weibo', 'weibo'), ('instagram', 'instagram'), ('twitter', 'twitter')], help_text='Social platform provider name', max_length=50),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.TextField(choices=[('video', 'video'), (None, 'unknown'), ('audio', 'audio'), ('photo', 'photo')], default='photo'),
        ),
        migrations.AlterField(
            model_name='mediainstance',
            name='quality',
            field=models.CharField(choices=[(0, 'thumb'), (20, 'high'), (10, 'low'), (100, 'origin')], default=100, max_length=50),
        ),
        migrations.AlterField(
            model_name='mediainstance',
            name='type',
            field=models.CharField(choices=[('video', 'video'), (None, 'unknown'), ('audio', 'audio'), ('photo', 'photo')], default='photo', max_length=50),
        ),
        migrations.AlterField(
            model_name='socialuser',
            name='provider',
            field=models.CharField(choices=[('', ''), ('weibo', 'weibo'), ('instagram', 'instagram'), ('twitter', 'twitter')], help_text='Social platform provider name', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='media',
            unique_together=set([('provider', 'rid', 'rcode')]),
        ),
        migrations.AlterUniqueTogether(
            name='socialuser',
            unique_together=set([('provider', 'rid', 'username')]),
        ),
    ]
