# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 15:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weinsta', '0007_auto_20171009_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.IntegerField(choices=[(0, 'new'), (100, 'done'), (10, 'ready'), (20, 'in progress')], db_index=True),
        ),
        migrations.AlterField(
            model_name='media',
            name='provider',
            field=models.CharField(choices=[('', ''), ('twitter', 'twitter'), ('weibo', 'weibo'), ('instagram', 'instagram')], help_text='Social platform provider name', max_length=50),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.TextField(choices=[('photo', 'photo'), ('audio', 'audio'), (None, 'unknown'), ('video', 'video')], default='photo'),
        ),
        migrations.AlterField(
            model_name='mediainstance',
            name='type',
            field=models.CharField(choices=[('photo', 'photo'), ('audio', 'audio'), (None, 'unknown'), ('video', 'video')], default='photo', max_length=50),
        ),
        migrations.AlterField(
            model_name='socialuser',
            name='provider',
            field=models.CharField(choices=[('', ''), ('twitter', 'twitter'), ('weibo', 'weibo'), ('instagram', 'instagram')], help_text='Social platform provider name', max_length=50),
        ),
    ]
