# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 10:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weinsta', '0008_auto_20171009_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, help_text='When the campaign created.'),
        ),
        migrations.AlterField(
            model_name='media',
            name='provider',
            field=models.CharField(choices=[('', ''), ('instagram', 'instagram'), ('twitter', 'twitter'), ('weibo', 'weibo')], help_text='Social platform provider name', max_length=50),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('', 'unknown'), ('video', 'video'), ('photo', 'photo'), ('audio', 'audio')], default='photo', max_length=50),
        ),
        migrations.AlterField(
            model_name='mediainstance',
            name='type',
            field=models.CharField(choices=[('', 'unknown'), ('video', 'video'), ('photo', 'photo'), ('audio', 'audio')], default='photo', max_length=50),
        ),
        migrations.AlterField(
            model_name='socialuser',
            name='provider',
            field=models.CharField(choices=[('', ''), ('instagram', 'instagram'), ('twitter', 'twitter'), ('weibo', 'weibo')], help_text='Social platform provider name', max_length=50),
        ),
    ]
