# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 10:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weinsta', '0009_auto_20171011_1824'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='begin',
            field=models.DateTimeField(blank=True, help_text='When will the campaign begin.', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='end',
            field=models.DateTimeField(blank=True, help_text='When will the campaign end.', null=True),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='providers',
            field=models.TextField(choices=[('', ''), ('instagram', 'instagram'), ('twitter', 'twitter'), ('weibo', 'weibo')], default='', help_text='Comma separated provider codes'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.IntegerField(choices=[(0, 'new'), (100, 'done'), (10, 'ready'), (20, 'in progress')], db_index=True, default=0),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
    ]
