# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 14:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weinsta', '0010_auto_20171011_1828'),
    ]

    operations = [
        migrations.CreateModel(
            name='Battle',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('provider', models.CharField(choices=[('', ''), ('instagram', 'instagram'), ('twitter', 'twitter'), ('weibo', 'weibo')], max_length=50)),
                ('started', models.BooleanField(default=False)),
                ('finished', models.BooleanField(default=True)),
            ],
        ),
        migrations.AlterField(
            model_name='campaign',
            name='providers',
            field=models.TextField(help_text='Comma separated provider codes'),
        ),
        migrations.AddField(
            model_name='battle',
            name='campaign',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='battles', to='weinsta.Campaign'),
        ),
    ]
