# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 06:47
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weinsta', '0011_auto_20171016_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('date', models.DateField(auto_now_add=True)),
                ('time', models.TimeField(auto_now_add=True)),
                ('hour', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='ActivityPerson',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('text', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='battle',
            name='post_id',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('', 'unknown'), ('photo', 'photo'), ('video', 'video'), ('audio', 'audio')], default='photo', max_length=50),
        ),
        migrations.AlterField(
            model_name='mediainstance',
            name='type',
            field=models.CharField(choices=[('', 'unknown'), ('photo', 'photo'), ('video', 'video'), ('audio', 'audio')], default='photo', max_length=50),
        ),
        migrations.AlterUniqueTogether(
            name='battle',
            unique_together=set([('provider', 'post_id')]),
        ),
        migrations.CreateModel(
            name='CommentActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='weinsta.Activity')),
                ('count', models.IntegerField()),
            ],
            bases=('weinsta.activity',),
        ),
        migrations.CreateModel(
            name='LikeActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='weinsta.Activity')),
                ('count', models.IntegerField()),
            ],
            bases=('weinsta.activity',),
        ),
        migrations.CreateModel(
            name='RePostActivity',
            fields=[
                ('activity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='weinsta.Activity')),
                ('count', models.IntegerField()),
            ],
            bases=('weinsta.activity',),
        ),
        migrations.AddField(
            model_name='activityperson',
            name='activity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weinsta.Activity'),
        ),
        migrations.AddField(
            model_name='activityperson',
            name='person',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weinsta.SocialUser'),
        ),
        migrations.AddField(
            model_name='activity',
            name='battle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weinsta.Battle'),
        ),
    ]
