# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 06:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weinsta', '0012_auto_20171025_1447'),
    ]

    operations = [
        migrations.AlterField(
            model_name='battle',
            name='finished',
            field=models.BooleanField(default=False),
        ),
    ]
