# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 07:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weinsta', '0013_auto_20171025_1459'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='activityperson',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='activityperson',
            name='person',
        ),
        migrations.RemoveField(
            model_name='commentactivity',
            name='activity_ptr',
        ),
        migrations.RemoveField(
            model_name='likeactivity',
            name='activity_ptr',
        ),
        migrations.RemoveField(
            model_name='repostactivity',
            name='activity_ptr',
        ),
        migrations.AlterField(
            model_name='battle',
            name='post_id',
            field=models.CharField(help_text='remote id of posted status for this battle', max_length=100),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('', 'unknown'), ('video', 'video'), ('photo', 'photo'), ('audio', 'audio')], default='photo', max_length=50),
        ),
        migrations.AlterField(
            model_name='mediainstance',
            name='type',
            field=models.CharField(choices=[('', 'unknown'), ('video', 'video'), ('photo', 'photo'), ('audio', 'audio')], default='photo', max_length=50),
        ),
        migrations.DeleteModel(
            name='ActivityPerson',
        ),
        migrations.DeleteModel(
            name='CommentActivity',
        ),
        migrations.DeleteModel(
            name='LikeActivity',
        ),
        migrations.DeleteModel(
            name='RePostActivity',
        ),
    ]
