# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-25 07:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weinsta', '0015_auto_20171025_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='activity',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weinsta.SocialUser'),
        ),
        migrations.AddField(
            model_name='activity',
            name='rid',
            field=models.CharField(blank=True, help_text='remote id of comment/repost status for this activity', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='text',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('comment', 'comment'), ('like', 'like'), ('repost', 'repost')], db_index=True, default='comment', max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('', 'unknown'), ('photo', 'photo'), ('audio', 'audio'), ('video', 'video')], default='photo', max_length=50),
        ),
        migrations.AlterField(
            model_name='mediainstance',
            name='type',
            field=models.CharField(choices=[('', 'unknown'), ('photo', 'photo'), ('audio', 'audio'), ('video', 'video')], default='photo', max_length=50),
        ),
    ]
