# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 06:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weinsta', '0017_auto_20171110_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='activity',
            old_name='date',
            new_name='datetime',
        ),
        migrations.RemoveField(
            model_name='activity',
            name='time',
        ),
        migrations.AddField(
            model_name='activity',
            name='tag',
            field=models.CharField(default='', help_text='The date time string (to hour). For grouping, labeling.', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='hour',
            field=models.IntegerField(help_text='Date time in int format (to hour). e.g 2017-10-12 14:32:12 -> 2017101214'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('repost', 'repost'), ('like', 'like'), ('comment', 'comment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('', 'unknown'), ('audio', 'audio'), ('photo', 'photo'), ('video', 'video')], default='photo', max_length=50),
        ),
        migrations.AlterField(
            model_name='mediainstance',
            name='type',
            field=models.CharField(choices=[('', 'unknown'), ('audio', 'audio'), ('photo', 'photo'), ('video', 'video')], default='photo', max_length=50),
        ),
    ]
