# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-10 06:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weinsta', '0018_auto_20171110_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='datetime',
            field=models.DateTimeField(help_text='When the activity data was collected'),
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('like', 'like'), ('comment', 'comment'), ('repost', 'repost')], max_length=50),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('', 'unknown'), ('photo', 'photo'), ('audio', 'audio'), ('video', 'video')], default='photo', max_length=50),
        ),
        migrations.AlterField(
            model_name='mediainstance',
            name='type',
            field=models.CharField(choices=[('', 'unknown'), ('photo', 'photo'), ('audio', 'audio'), ('video', 'video')], default='photo', max_length=50),
        ),
    ]
