# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-02 07:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weinsta', '0019_auto_20171110_1430'),
    ]

    operations = [
        migrations.AddField(
            model_name='battle',
            name='link',
            field=models.TextField(default='', help_text='link for the status'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='activity',
            name='type',
            field=models.CharField(choices=[('repost', 'repost'), ('like', 'like'), ('comment', 'comment')], max_length=50),
        ),
        migrations.AlterField(
            model_name='media',
            name='type',
            field=models.CharField(choices=[('', 'unknown'), ('video', 'video'), ('photo', 'photo'), ('audio', 'audio')], default='photo', max_length=50),
        ),
        migrations.AlterField(
            model_name='mediainstance',
            name='type',
            field=models.CharField(choices=[('', 'unknown'), ('video', 'video'), ('photo', 'photo'), ('audio', 'audio')], default='photo', max_length=50),
        ),
    ]
